import { Geist, Geist_Mono, Lato } from "next/font/google";
import "./globals.css";
import Navber from "./components/Navber";
import { Weight } from "lucide";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const lato = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={`${lato.className} antialiased`}>
        <Navber />
        {children}
        <Footer />
      </body>
    </html>
  );
}
